### ISSUE TITLE
OpenCV: terminate handler is called! The last OpenCV error is:

### ISSUE THREAD

**Issue by kevinyou278** [liuchang0523/sfrmat3_cpp#1]
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.5.2) Error: Assertion failed (m.dims >= 2) in Mat, file C:\opencv\sources\opencv-4.5.2\modules\core\src\matrix.cpp, line 751

**Comment by liuchang0523** [comment]
自己调试一下，你能行的

**Comment by kevinyou278** [comment]
> 自己调试一下，你能行的

哈哈，谢谢，已运行学习了，第一次接触
